### ISSUE TITLE
腾讯自选股一直不行，不知道怎么回事

### ISSUE THREAD

**Issue by Anima-No** [Yiov/wool#24]
一直报错
腾讯自选股 新版, 错误!
TypeError: Cannot read properties of null (reading '1')
    at /ql/scripts/Yiov_wool/txstock_new.js:396:52
    at Array.forEach (<anonymous>)
    at getEnvParam (/ql/scripts/Yiov_wool/txstock_new.js:390:34)
    at initAccountInfo (/ql/scripts/Yiov_wool/txstock_new.js:438:15)
    at /ql/scripts/Yiov_wool/txstock_new.js:184:15
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

看着好像是url的问题，但是我export TxStockAppUrl='https://wzq.tenpay.com/cgi-bin/activity_task_daily.fcgi?action=home&type=routine&··································‘
这应该是没问题的吧，吧整串请求链接复制给TxStockAppUrl

![image](https://user-images.githubusercontent.com/44191876/159123753-ed4dc4ea-656c-4fdf-adc0-d1bd24ee9d65.png)

**Comment by Anima-No** [comment]
不对，这个是JSON的问题，但是我用了两个转化的工具，都一样，
https://wejson.cn/header2json/
https://uutool.cn/header2json/

你那个文档的那个已经不行了，这个我重新找了2个

**Comment by Yiov** [comment]
对，JSON的问题，我文档那个转换用半年了，最近几天不行了了，我在开头列举了另外两个

**Comment by Anima-No** [comment]
> 对，JSON的问题，我文档那个转换用半年了，最近几天不行了了，我在开头列举了另外两个

那我现在这个抓的应该也没问题，转化虽然文档写的那个暂时不能用了，我找了别的，也成功转化了，还是跑不了脚本，这个是js问题吗，还是我这边抓的有问题

**Comment by Anima-No** [comment]
> 对，JSON的问题，我文档那个转换用半年了，最近几天不行了了，我在开头列举了另外两个

应该是我的问题，我抓到的包，好像没有ts_sid这个字段，所以报错了

**Comment by Yiov** [comment]
你看下是不是公众号和app弄混了

**Comment by Anima-No** [comment]
> 你看下是不是公众号和app弄混了

终于可以了，你文档可以改一下，
APP跟微信的请求头header去->zqact.tenpay.com 这个域名底下复制一个请求头部回来就可以，这个头部内有pgv_pvid跟ts_sid跟ts_uid这三个字段，我刚刚全局找了一下就是这个域名底下的，放进去居然成功跑起来了

**Comment by Yiov** [comment]
好的 感谢反馈 ，我明天看下，我因为很早前抓的，一直用的老版
